models.settings.SystemSetting(stng_ratingsRefresh):
    stg_key: "ratingsRefreshTimeGap"
    stg_value: "30"
    isDefaultSetting: true
models.settings.SystemSetting(stng_pingTime):
    stg_key: "pingTime"
    stg_value: "400000"
    isDefaultSetting: true
models.settings.SystemSetting(stng_default_city_id):
    stg_key: "defaultCityId"
    stg_value: "1"
    isDefaultSetting: true    
models.settings.SystemSetting(stng_guessCity):
    stg_key: "guessCityByIpEnabled"
    stg_value: "false"
    isDefaultSetting: true    
models.users.SystemAdministrator(usr_admin):
    name: Admin
    surname: Admin
    phoneNumber: "+380630683088"
    miscInfo: admin
    email: admin@gmail.com
    login: admin
    password: "271828183"
    userStatus: ACTIVE
    joinDate: 2010-09-08
    lastLoginDate: 2010-09-08

